### ISSUE TITLE
broken links MODS_ConvNet/STM_Code/download_files.md 

### ISSUE THREAD

**Issue by adjs** [santiagolopezg/MODS_ConvNet#1]
Hi @santiagolopezg,

Thanks for making the code and data of your publication available.
Links to download weights for the five resc_CNN models, 2lab_CNN_1, 2lab_CNN_2, and 2lab_CNN_3 are broken.

**Comment by santiagolopezg** [comment]
Hi @adjs,

Thanks for catching this -- I've looked into it and there are a few more broken links. 

This seems to have been caused by a [security update on from Google Drive regarding file sharing](https://support.google.com/drive/answer/10729743?p=update_drives_user&visit_id=637794443296663015-4061791844&rd=1#zippy=%2Chow-will-this-security-update-change-access-to-my-impacted-files). 

I'll work on updating the links asap.

**Comment by santiagolopezg** [comment]
Hi @adjs,

I think the issue is solved with commit 862d3e8 . Let me know if that fixes it for you!

**Comment by adjs** [comment]
Hi @santiagolopezg ,

Now I can see the google drive download link, but I received a 403 code (forbidden) when I clicked in the download button.

**Comment by santiagolopezg** [comment]
@adjs ,
I see this on my end too. I'm really sorry for the inconvenience -- I'll figure out a workaround asap and let you know.

**Comment by santiagolopezg** [comment]
Hi @adjs ,

I found a quick workaround to the issue, and wrote an brief _how to_ in commit [e8a227c](https://github.com/santiagolopezg/MODS_ConvNet/commit/e8a227c7073f0874f262b26168109d91144db2fa). 

Explicitly, the fix is as follows:

If shown the Google Error 403, you can copy the `&resourcekey=TK` snippet from the urls provided for file download, paste them into the search bar at the end of the url (as shown below), and hit enter -- that should start the download.

Old url from Google Error 403 site: `https://drive.google.com/u/0/uc?export=download&confirm={changes_everytime}&id=0B8c8rHDbaNImUkZQTnkwaHVFeFk`

The resulting url will be something like: `https://drive.google.com/u/0/uc?export=download&confirm={changes_everytime}&id=0B8c8rHDbaNImUkZQTnkwaHVFeFk&resourcekey=0-4fkRMRCT3Hc30stpQNOaKA`

I hope this solves things, at least momentarily.

**Comment by adjs** [comment]
thanks, @santiagolopezg.
I downloaded the files following the new instructions.
